### ISSUE TITLE
unraid自带的docker好像不支持docker-compose.yml文件安装，需要升级为完全版

### ISSUE THREAD

**Issue by tingyue-wu** [Sincejunly/officeaanglist#1]
unraid自带的docker好像不支持docker-compose.yml文件安装，需要升级为完全版
还有单位里边用的是win服务器，我装的也是alist和onlyoffice的win版本，可惜只能浏览文件无法多用户编辑。
也试过win下面安装docker，但是没成功，电脑卡的不得了。
看来要专门弄台nas做文件服务器了，好安装大佬的这个集成工具。为你点赞！

**Comment by homuraLan** [comment]
新版本可能解决今天晚上可能彻底完工，window理论上没问题

**Comment by homuraLan** [comment]
我想想到时候写个docker run

**Comment by tingyue-wu** [comment]
> 我想想到时候写个docker run

太给力了。

**Comment by homuraLan** [comment]
> unraid自带的docker好像不支持docker-compose.yml文件安装，需要升级为完全版 还有单位里边用的是win服务器，我装的也是alist和onlyoffice的win版本，可惜只能浏览文件无法多用户编辑。 也试过win下面安装docker，但是没成功，电脑卡的不得了。 看来要专门弄台nas做文件服务器了，好安装大佬的这个集成工具。为你点赞！

我觉得你研究一下怎么装更合适
